/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestRouteImport } from './routes/request'
import { Route as BoothCodeRouteImport } from './routes/booth.$code'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothCodeRoute = BoothCodeRouteImport.update({
  id: '/booth/$code',
  path: '/booth/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/booth/$code': typeof BoothCodeRoute
  '/r/$code': typeof RCodeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/booth/$code': typeof BoothCodeRoute
  '/r/$code': typeof RCodeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/booth/$code': typeof BoothCodeRoute
  '/r/$code': typeof RCodeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/request' | '/booth/$code' | '/r/$code' | '/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/request' | '/booth/$code' | '/r/$code' | '/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/request'
    | '/booth/$code'
    | '/r/$code'
    | '/spotify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestRoute: typeof RequestRoute
  BoothCodeRoute: typeof BoothCodeRoute
  RCodeRoute: typeof RCodeRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth/$code': {
      id: '/booth/$code'
      path: '/booth/$code'
      fullPath: '/booth/$code'
      preLoaderRoute: typeof BoothCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestRoute: RequestRoute,
  BoothCodeRoute: BoothCodeRoute,
  RCodeRoute: RCodeRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
